### PR TITLE
Adding Repairnator page

### PR DESCRIPTION
**Pull request by phkrief**
Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@phkrief I created https://bugs.eclipse.org/bugs/show_bug.cgi?id=567445 to set a default logo for projects without a logo. Your problem should be fixed on that bug is done.

**Comment by chrisguindon** [comment]
Quick update: We have a patch for the API and it's almost done. I requested more changes to it but I expect this to go live mid next week.

**Comment by chrisguindon** [comment]
@phkrief The patch is live, you should see the update but you might need to update your PR in order to trigger a website re-build.

**Comment by phkrief** [comment]
I could not figure out how to merge my existing branch with the master so I created a new one and copied my changes into the new branch.
I guess a new a training on this one ;-)
Thanks

**Pull request closed without merging**
