### PR TITLE
Eclipse Research - Branding and Jumbotron Update #31

### LINKED ISSUE #31: Eclipse Research - Branding and Jumbotron Update
We've finalized the Research @ Eclipse branding and jumbotron image for this page: https://www.eclipse.org/org/research/

Please find the attached mockup and assets. We'd like to update the Twitter account at the same time that these page updates go live, so keep us posted on the timeline: https://twitter.com/ResearchEclipse 

This should be updated ideally before the end of September and prior to EclipseCon on October 19th at the very latest.

Example-Research @Eclipse

[research-web-assets.zip](https://github.com/EclipseFdn/eclipse.org-research/files/5092522/research-web-assets.zip)

### PR DESCRIPTION
**Pull request by autumnfound**
Fixes #31

Added new logo image, jumbotron banner image, and set them in the
configs. Updates made to make the max size of logo larger to fit more
content.

Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Review by ChristieWittEclipse — COMMENTED** [review]
Looks perfect +1

**Comment by autumnfound** [comment]
How would you like to sync this update with the Twitter banner update?

**Comment by ChristieWittEclipse** [comment]
@autumnfound @jph152 will update the Twitter graphics in sync with you. Just let him know approximately what time the page updates will go live.

**Comment by autumnfound** [comment]
@ericpoirier let us know when you think its good to go live and then we can sync all of this up!

**Comment by ericpoirier** [comment]
> @ericpoirier let us know when you think its good to go live and then we can sync all of this up!

I think this looks good.

We can go live when both of you are ready.

**Comment by jph152** [comment]
> > @ericpoirier let us know when you think its good to go live and then we can sync all of this up!
> 
> I think this looks good.
> 
> We can go live when both of you are ready.

I'm good to update the Twitter account. Maybe in 20 min?

**Comment by jph152** [comment]
@autumnfound @ericpoirier Ready to update when you are

**Review by ericpoirier — APPROVED** [review]

**Comment by autumnfound** [comment]
@jph152 apologies, I didn't see the notification until now. I double-checked with Eric, and we're good to merge when you give the word!

**Comment by jph152** [comment]
@autumnfound all good! I forgot to tag you guys. I can make the updates now

**Comment by autumnfound** [comment]
@jph152 update made! It'll be live in a couple of minutes :)

**Pull request merged**
