### PR TITLE
Site re-vamp

### PR DESCRIPTION
**Pull request by autumnfound**

### CODE REVIEW

**Comment by autumnfound** [comment]
@phkrief here is a PR with a preview site

**Comment by phkrief** [comment]
Thx @autumnfound 
I see some issues in the build but I can't access the details.  Is it expected?
SO I don't know if the problem comes from my own changes.
Thx

**Comment by autumnfound** [comment]
> Anonymous (philippe.krief@****.org) is not covered by the necessary legal agreements in order to proceed.

I'm pretty sure you had proper sign off earlier though...Can you double check your eclipse account to make sure everything is still lined up?

**Comment by chrisguindon** [comment]
@phkrief Do  not worry about the failure with Jenkins! There is a known issue where jenkins will always fail on the first build. This is true for all our hugo sites.

We should be fine if netlify and travis-ci are successful!

**Comment by chrisguindon** [comment]
It's good practice to include the sign-off by as mentioned by @autumnfound but it's not required here!

**Comment by phkrief** [comment]
> > Anonymous (philippe.krief@****.org) is not covered by the necessary legal agreements in order to proceed.
> 
> I'm pretty sure you had proper sign off earlier though...Can you double check your eclipse account to make sure everything is still lined up?

Yes, I certainly forgot to add a sign off in one commit. Sorry about that

**Comment by phkrief** [comment]
@autumnfound I don't see my last changes including the Sparta project.
I suspect that some of my pull requests are not already included in your version.
Right?

**Comment by autumnfound** [comment]
> @autumnfound I don't see my last changes including the Sparta project.
> I suspect that some of my pull requests are not already included in your version.
> Right?

Spartan was not part of your Pull Request. Did you push it up after the PR was merged in perhaps?

**Pull request merged**
